### ISSUE TITLE
Audit veGNO.sol

### ISSUE THREAD

**Issue by auryn-macmillan** [hundred-finance/hundred-dao#1]

**Comment by SHA-2048** [comment]
@auryn-macmillan Thanks for opening the issue. Would be great if you share a bit more details on the concerns you have about the code. Is there any particular issue you saw in the current implementation?

**Comment by auryn-macmillan** [comment]
Hey @SHA-2048, sorry for the lack of content on the issue. I opened it originally because we were adding it to Gnosis' audit pipeline and I needed an issue to import into our Github project. Should have added that information here to make it a little more obvious to everyone else though :smile:

**Comment by SHA-2048** [comment]
No worries, I assumed it's related to the audit started by gnosis team, which was discussed on private chat. So I closed it. Audit is now done and I included the report on this repo
